### ISSUE TITLE
Recursion bug when refreshing a page with data already entered

### ISSUE THREAD

**Issue by ianastewart** [FlipperPA/django-tempus-dominus#2]
Create a Django form with a date field using the datepicker (format option = DD/MM/YYYY though this is not material) and a time field using the timepicker. Load the page. Both widgets work correctly. 
![image](https://user-images.githubusercontent.com/7371426/43771138-2cd3b49a-9a36-11e8-89c2-f3a29e77bec9.png)
But if you then refresh the page without first saving it, the date field is preloaded with the previously selected date and also displays a time of 12am.
![image](https://user-images.githubusercontent.com/7371426/43771196-5532e9d8-9a36-11e8-8bb9-f97eaf7b03be.png)
 Similarly the time field displayes a full data and time. An attempt to change the date results in a jQuery error: too much recursion. See trace from Firefox below:

jQuery.Deferred exception: too much recursion 
xe@http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.0/moment.min.js:1:7138
Fe@http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.0/moment.min.js:1:8658
@http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.0/moment.min.js:1:7668
I/E[t[0]]@http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.0/moment.min.js:1:4760
A/V[t]</<@http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.0/moment.min.js:1:5165
A@http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.0/moment.min.js:1:5199
ln.format@http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.0/moment.min.js:1:30586
f</u</i.prototype._setValue@http://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js:6:8126
f</u</i.prototype._int@http://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js:6:6984
i@http://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js:6:6495
k@http://cdn…
 undefined jquery-3.3.1.min.js:2:30920
[Show/hide message details.] too much recursion[Learn More] moment.min.js:1:7138
xe
http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.0/moment.min.js:1:7138
Fe
http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.0/moment.min.js:1:8658
<anonymous>
http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.0/moment.min.js:1:7668
I/E[t[0]]
http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.0/moment.min.js:1:4760
A/V[t]</<
http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.0/moment.min.js:1:5165
A
http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.0/moment.min.js:1:5199
ln.format
http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.0/moment.min.js:1:30586
f</u</i.prototype._setValue
http://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js:6:8126
f</u</i.prototype._int
http://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js:6:6984
i
http://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js:6:6495
k
http://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js:6:29086
l</k._jQueryHandleThis
http://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js:7:22196
l</k._jQueryInterface
http://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js:7:22406
<anonymous>
http://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js:7:22730
dispatch
https://code.jquery.com/jquery-3.3.1.min.js:2:41720
add/y.handle
https://code.jquery.com/jquery-3.3.1.min.js:2:39774
trigger
https://code.jquery.com/jquery-3.3.1.min.js:2:69549
trigger/<
https://code.jquery.com/jquery-3.3.1.min.js:2:70138
each
https://code.jquery.com/jquery-3.3.1.min.js:2:2571
each
https://code.jquery.com/jquery-3.3.1.min.js:2:1238
trigger
https://code.jquery.com/jquery-3.3.1.min.js:2:70117
f</u</i.prototype._notifyEvent
http://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js:6:10392
f</u</i.prototype._setValue
http://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js:6:8542
f</u</i.prototype._int
http://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js:6:6984
i
http://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js:6:6495
k
http://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js:6:29086
l</k._jQueryHandleThis
http://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js:7:22196
l</k._jQueryInterface
http://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js:7:22406
<anonymous>
http://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js:7:22730
dispatch
https://code.jquery.com/jquery-3.3.1.min.js:2:41720
add/y.handle
https://code.jquery.com/jquery-3.3.1.min.js:2:39774
trigger
https://code.jquery.com/jquery-3.3.1.min.js:2:69549
trigger/<
https://code.jquery.com/jquery-3.3.1.min.js:2:70138
each
https://code.jquery.com/jquery-3.3.1.min.js:2:2571
each
https://code.jquery.com/jquery-3.3.1.min.js:2:1238
trigger
https://code.jquery.com/jquery-3.3.1.min.js:2:70117
f</u</i.prototype._notifyEvent
http://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js:6:10392
f</u</i.prototype._setValue
http://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js:6:8542

**Comment by FlipperPA** [comment]
Thanks for the report! Could you let me know what OS and browser you are using? The bug should be squashed but it sounds like I'll need to use the same OS and browser to reproduce the browser autofill which is triggering the bug. @ianastewart

**Comment by FlipperPA** [comment]
@ianastewart We're overdue for an upgrade to the underlying Tempus Dominus library, so now may be the time! I'll try to get a chance to look at it today and report back.

**Comment by ianastewart** [comment]
I have investigated this bug futher and now know the cause. It's actually a side effect of another more serious bug that happens on all browsers.
Rendering date fields that have an existing value (e.g. in an Update view) does not work if using anything other than standard formatting (I use DD/MM/YYYY) . Rendering time fields with existing values never works - it is always blank, and datetime also has issues.
The answer is to set the existing values by passing a moment object in the options string. 
Fixing it was tricky - the type of the value object that is passed to render changes from date or datetime to a formatted string is a form gets submitted with errors and rerendered
I have resolved all this now and will send a pull request tomorrow. - Too late here in the UK now.

**Comment by FlipperPA** [comment]
@ianastewart That's great news! I should have scrolled down further, as I've just been trying to reproduce the bug on my setup:

```python
    start_date = forms.DateField(
        label='Start Date',
        initial=None,
        required=False,
        widget=DatePicker(),
    )
    end_date = forms.DateTimeField(
        label='End Date',
        initial=philly_today().strftime("%G-%m-%d 12:34:56"),
        required=False,
        widget=DateTimePicker(),
    )
```

I've also just finished an upgrade to the latest / greatest Tempus Dominus version (no longer alpha), which I'll push to master now. Once we get your P.R. in, I'll publish a new version. I'm also moving to a sub-semver numbering scheme, so the new version will be `5.0.1.0` (the Tempus Dominus version + `.0`).

**Comment by FlipperPA** [comment]
Thanks again @ianastewart - I have published to PyPI just now as version `5.0.1.0`. I haven't been able to reproduce the original bug seen in Firefox - did you PR fix the original issue? I was unclear from the text in the PR. If this fixes it, I'll go ahead and close this issue.

**Comment by ianastewart** [comment]
Sadly no,  the PR did not completely fix the original issue. It fixed bugs that I found while trying to track down the original bug. They were relating to formatting problems and fixing then removed the javascript recursion error. But in Firefox, if you are displaying a date in a field with datetimepicker attached and you refresh the page, the field goes blank. A subsequent refresh restores the correct values.
I’d like to track that down – I think it must be related to differences in the event handling between browsers. But I don’t have the time and/or necessary knowledge right now.

If you go to my repo https://github.com/ianastewart/test-django-tempus-dominus there is a test program that reproduces the bug

**Comment by ianastewart** [comment]
Closing because it's a bug in the underlying tempus dominus library.
